import unittest

from . import assertPopen


class HelpTest(unittest.TestCase):
    def test_help(self):
        output = assertPopen(['mike', 'help'])
        self.assertRegex(
            output, (r'^usage: mike \[-h\] \[--version\] \[--debug\] '
                     r'COMMAND \.\.\.')
        )

    def test_help_subcommand(self):
        output = assertPopen(['mike', 'help', 'deploy'])
        self.assertRegex(output, r'^usage: mike deploy')

    def test_help_subcommand_extra(self):
        output = assertPopen(['mike', 'help', 'deploy',
                              '--ignore-remote-status'])
        self.assertRegex(output, r'^usage: mike deploy')

    def test_help_paragraph_formatter(self):
        output = assertPopen(['mike', 'help', 'props'])
        self.assertRegex(output, r'^usage: mike props')
        self.assertRegex(output, ('(?m)^Get or set properties for the ' +
                                  'specified version\\.\n\nWhen getting'))


class GenerateCompletionTest(unittest.TestCase):
    def test_completion(self):
        output = assertPopen(['mike', 'generate-completion', '-sbash'])
        self.assertRegex(output, r'(?m)^# AUTOMATICALLY GENERATED by `shtab`')
